embedding_model:
  name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  dimension: 384
  
llm_model:
  name: "gpt-3.5-turbo"
  max_tokens: 800
  temperature: 0.7
  
fine_tuning:
  model: "gpt-3.5-turbo"
  epochs: 3
  batch_size: 1
  learning_rate_multiplier: 2